name: harold
favicon: null
layout_spectrum: 0.017232837388291955
typography_spectrum: 0.8544977104756981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4988750771153718
  lightness: 0.8765046284534037
  saturation: 0.34861070197075605
  rhythmicContrast: 0.5405264869332314
purpose: []
